School/Controllers/SchoolClassesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using School.Data;
using School.Models;
using School.Models.ViewModels;
using School.Services;

namespace School.Controllers
{
    [Authorize(Roles ="Admin")]

    public class SchoolClassesController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly UserManager<ApplicationUser> _userManager;
        private readonly IIdentityService _identityService;

        public ApplicationUser Teacher { get; set; }


        public SchoolClassesController(ApplicationDbContext context, UserManager<ApplicationUser> userManager, IIdentityService identityService)
        {
            _context = context;
            _userManager = userManager;
            _identityService = identityService;
        }

        // GET: SchoolClasses
        public async Task<IActionResult> Index()
        {
            var classes = await _context.SchoolClasses.ToListAsync();
            var students = _context.StudentSchools.ToList();

            foreach (var schoolClass in classes)
            {
                
               schoolClass.Teacher = await _userManager.Users.FirstOrDefaultAsync(ap => ap.Id == schoolClass.TeacherId);
             
                //schoolClass.Students = (ICollection<ApplicationUser>)await _context.StudentSchools.FirstOrDefaultAsync(s => s.SchoolClassId == schoolClass.Id);

                foreach (var student in students)
                {
         
                   
                    ViewBag.Students = (await _userManager.GetUsersInRoleAsync("Student"), student.Student.DisplayName, student.SchoolClassId = schoolClass.Id);
                   

                }



            }

          



            return View(classes);
        }

      

        // GET: SchoolClasses/Details/5

        public async Task<IActionResult> Details(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var schoolClass = await _context.SchoolClasses
                .FirstOrDefaultAsync(m => m.Id == id);

            var students = _context.StudentSchools.ToList();

            schoolClass.Teacher = await _userManager.Users.FirstOrDefaultAsync(ap => ap.Id == schoolClass.TeacherId);


            foreach (var student in students)
            {


                ViewBag.Students = (await _userManager.GetUsersInRoleAsync("Student"), student.Student.DisplayName, student.SchoolClassId = schoolClass.Id);


            }





            if (schoolClass == null)
            {
                return NotFound();
            }

            return View(schoolClass);
        }

        // GET: SchoolClasses/Create
        public async Task <IActionResult> Create()
        {
            var teachers = await _userManager.GetUsersInRoleAsync("Teacher");

            ViewData["TeacherId"] = new SelectList(await _userManager.GetUsersInRoleAsync("Teacher"), "Id", "DisplayName");
            //ViewData["Teachers"] = new SelectList(_context.Users, "Id", "DisplayName", schoolClass.Teacher);

            ViewBag.Teachers = teachers;
         
            return View();
        }

        // POST: SchoolClasses/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Year, TeacherId")] SchoolClass schoolClass)
        {
            if (ModelState.IsValid)
            {
                _context.Add(schoolClass);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }

            ViewData["TeacherId"] = new SelectList(_context.Users, "Id", "TeacherId", schoolClass.TeacherId);

            return View(schoolClass);
        }

        // GET: SchoolClasses/Edit/5
        public async Task<IActionResult> Edit(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var schoolClass = await _context.SchoolClasses.FindAsync(id);
            if (schoolClass == null)
            {
                return NotFound();
            }
            return View(schoolClass);
        }

        // POST: SchoolClasses/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(string id, [Bind("Id,Year")] SchoolClass schoolClass)
        {
            if (id != schoolClass.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(schoolClass);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!SchoolClassExists(schoolClass.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(schoolClass);
        }

        // GET: SchoolClasses/Delete/5
        public async Task<IActionResult> Delete(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var schoolClass = await _context.SchoolClasses
                .FirstOrDefaultAsync(m => m.Id == id);
            if (schoolClass == null)
            {
                return NotFound();
            }

            return View(schoolClass);
        }

        // POST: SchoolClasses/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(string id)
        {
            var schoolClass = await _context.SchoolClasses.FindAsync(id);
            _context.SchoolClasses.Remove(schoolClass);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool SchoolClassExists(string id)
        {
            return _context.SchoolClasses.Any(e => e.Id == id);
        }
    }
}

School/Views/Shared/_AdminPartial.cshtml
@using School.Data
@using Microsoft.AspNetCore.Identity
@inject SignInManager<ApplicationUser> SignInManager
@inject UserManager<ApplicationUser> UserManager

@if (SignInManager.IsSignedIn(User))
{
    @if (User.IsInRole("Admin"))
    { 
<div class="bg-white">
    <div class="container ">
        <ul class="nav justify-content-end">
            <li class="nav-item">
                <a class="nav-link " asp-area="" asp-controller="AdminContoller" asp-action="AddTeacher">AddTeacher</a>
            </li>
            <li class="nav-item">
                <a class="nav-link " asp-area="" asp-controller="AdminContoller" asp-action="AddStudent">AddStudent</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" asp-area="" asp-controller="SchoolClasses" asp-action="Index">Classes</a>
            </li>

        </ul>
    </div>
</div>
       

    }
}

School/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - School</title>
    @*<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-giJF6kkoqNQ00vy+HMDP7azOuL0xtbfIcaT9wjKHr8RbDVddVHyTfAAsrekwKmP1" crossorigin="anonymous">*@
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="/css/site.css" />
    @*<link href="@Url.Content("~/css/mystyle.css")" rel="stylesheet" type="text/css" />*@
    <link rel="stylesheet" href="/css/mystyle.css" />
</head>
<body>
    <header>

        <partial name="_AdminPartial" />

        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <img src="https://upload.wikimedia.org/wikipedia/commons/3/35/Ylen_logo.svg" class="navbar-brand logo" alt="">
                <a class="navbar-brand " asp-area="" asp-controller="Home" asp-action="Index">School</a>

                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>


                <partial name="_LoginPartial" />

            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - School - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    @*<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/js/bootstrap.bundle.min.js" integrity="sha384-ygbV9kiqUc6oa4msXn9868pTtWMgiQaeYH7/t7LECLbyPA2x65Kgf80OJFdroafW" crossorigin="anonymous"></script>*@
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

School/Views/Shared/_StudentPartial.cshtml
@model School.Models.SchoolClass




@if (Model.StudentsSchool != null)
{
    @foreach (var student in Model.StudentsSchool)
    {
        <div class="card col-3">
            <img src="https://upload.wikimedia.org/wikipedia/commons/6/63/Upload_free_image_notext.svg" class="card-img-top round" alt="...">
            <div class="card-body border">
                <h5 class="card-title">  @Html.DisplayFor(model => student.Student.DisplayName)</h5>
                <p class="card-text"> @Html.DisplayNameFor(model => model.Students)</p>

            </div>
        </div>

    }
}

School/Views/Shared/_TeacherPartial.cshtml
@model School.Models.SchoolClass



<div class="card col-3  ">
    <img src="https://upload.wikimedia.org/wikipedia/commons/6/63/Upload_free_image_notext.svg" class="card-img-top round" alt="...">
    <div class="card-body border">
        <h5 class="card-title">  @Html.DisplayFor(model => model.Teacher.DisplayName)</h5>
        <p class="card-text">  @Html.DisplayNameFor(model => model.Teacher)</p>

    </div>
</div>